### ISSUE TITLE
Why Git HUB for backlog?

### ISSUE THREAD

**Issue by ted-grasela** [ki-analysis/Rally-Backlog#4]
HI Mary,
Just testing Git Hub by asking why are we moving back log to here instead of keeping in Synapse?
Ted
@ki-analysis/rally-14

**Comment by hafen** [comment]
@ted-grasela in addition to GitHub having intuitive kanban functionality, the primary use of GitHub will be for data scientists collaborating on code for rallies and other analyses, so it's convenient to do both in the same place.

**Comment by ted-grasela** [comment]
Thanks Ryan and Mary, 
Looking forward to learning more as we work through the neuro rally. 
Ted 

-- 
Ted Grasela, PharmD, PhD 
President 
Cognigen: +1-716-633-3463 ext. 227 | [ http://www.cognigencorp.com/ | Website ]

**Comment by helenelizabetho** [comment]
Hi Mary! Joined successfully :)

**Comment by whiteme1** [comment]
Hooray
